site:
  title: Couchbase Documentation Style Guide
  url: https://sarahlweton.github.io/cb-vale-style-guide/styleguide/
  robots: disallow
  start_page: styleguide:ROOT:index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: styleguidepages
  - url: .
    branches: HEAD
    start_path: ui-ux
  - url: .
    branches: HEAD
    start_path: pendo
ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
output: 
  clean: true
  dir: ./docs
